apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bedrock-dev-view-binding
  namespace: retail-app
subjects:
  - kind: User
    name: bedrock-dev-view
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
